### ISSUE TITLE
modif vue advanced.html

### ISSUE THREAD

**Issue by thierry-thevenet** [thierrythevenet1963/Talao#234]
manque probablement le code pour private keys dans user_advanced et Blockchain Information ne fonctionne plus.

**Comment by thierry-thevenet** [comment]
ok j ai commpris que private key etat un clipboard mais ce n est pas evident parcequ il a etet positionné comme un titre

**Comment by AlexLeclerc102** [comment]
Je n'ai pas le même comportement sur ma version de test a cause d'un </div> mal placé qui fait que l'accordéon se termine trop tot
Le comportement suivant:
![Capture d’écran du 2020-10-05 15-16-50](https://user-images.githubusercontent.com/72029514/95084214-dc83c000-071d-11eb-845d-e8333159771f.png)
est présent sur la dernière version de la branche alex

**Comment by thierry-thevenet** [comment]
j ai fait quelques modifs pour ça foncitonne mais je n ai pas reellement trouver la source du pb. Probablement l integration du clipboard dans le titre de l accordeon est problematique.(private key)  il faudra trouver une autre solution a terme. (pas urgent)

**Comment by thierry-thevenet** [comment]
je ne retrouve plus le fichier advanced.html avec la modif
