### ISSUE TITLE
Loading et manque d'info sur un formulaire

### ISSUE THREAD

**Issue by Drax35** [thierrythevenet1963/Talao#248]
Si il manque une info sur un formulaire, en appuyant sur le bouton soumettre, le formulaire indique qu'il manque une info mais reste en loading. Loading ne devrait être déclenché que une fois toutes les infos remplies

**Comment by thierry-thevenet** [comment]
c est un probleme javascript
cf le code de in_progress_button.js an loading_button.js dans /static
