### ISSUE TITLE
Pouvoir changer le "Privacy Setting" d'un document une fois uploadé

### ISSUE THREAD

**Issue by Drax35** [thierrythevenet1963/Talao#265]
Aujourd'hui il faut le supprimer et le réuploader

**Comment by thierry-thevenet** [comment]
impossible sur la blockchain

**Comment by Drax35** [comment]
Certes mais je pensais plus une fonction qui le fait automatiquement, duplication du document sous le nouveaux privacy settings et suppression de l'ancien par exemple (qui n'est pas vraiment supprimé mais bon ...)

**Comment by thierry-thevenet** [comment]
il faut recharger le document d origine (intervention du user) pour eventellement l'encrypter ou pas et ensuite l envoyer sur la blockchain.
