### ISSUE TITLE
route QRcode, lien ?

### ISSUE THREAD

**Issue by thierry-thevenet** [thierrythevenet1963/Talao#280]
Dans le main.py de ton repo il y a avec un lien sur http://192.168.1.29:3000/resume/?workspace_contract=0x0506c3492bd29C609acE3188cad19857F5Ea3833")

@app.route('/user/download_QRCode/', methods=['GET', 'POST'])
def download_QRCode():
    QRCode.get_QRCode(mode, "http://192.168.1.29:3000/resume/?workspace_contract=0x0506c3492bd29C609acE3188cad19857F5Ea3833")
    filename = 'QRCode_with_Logo.png'
    return send_from_directory(mode.uploads_path,
                               filename, as_attachment=True)

**Comment by AlexLeclerc102** [comment]
Il faut remplacer par :  mode.server  + "resume/?workspace_contract=" + session['workspace_contract']
