### ISSUE TITLE
Mail création compte

### ISSUE THREAD

**Issue by Drax35** [thierrythevenet1963/Talao#281]
retour : "Dans le mail que l'on reçoit lors de la création du profil "your first password is identity, change it as soon as possible", je me suis demandée si j'avais compris la phrase à savoir est ce que je remet mon nom ou est ce que le mdp est le mot "identity" ? juste ajouter " : " devant, ça éclaircirait le sujet."

**Comment by thierry-thevenet** [comment]
0.9.8
