### ISSUE TITLE
Expériences profil

### ISSUE THREAD

**Issue by Drax35** [thierrythevenet1963/Talao#282]
retour : "elles s'enregistrent dans l'ordre d'ajout et non par date de la plus récente à la plus ancienne j'ai l'impression ? je trouverais cela plus logique de mettre la plus récente en haut pour faciliter la lecture.
Pour info le temps d'enregistrement de mes experiences a été un peu long (5/10 secondes, je n'ai pas compté)"

L'ordre anti chronologique est déjà utilisé sur le cv vue extérieure

**Comment by thierry-thevenet** [comment]
elles sont effectivement affichées dans  l'ordre d'enregistrement.
le "temps d 'enregistrement"  est probablement de l ordre de 5s++ (temps d'une transaction + de propagation sur le reseau). On peut donner l impression que c est immediat en faisant de l' asynchrone mais on aura un petit risque de rater le receipt d'une  transaction failed.

**Comment by thierry-thevenet** [comment]
pas si simple de desynchroniser : en desynchronisant on a pas la possibilite de recuperer l id du document (event) et donc la mise a jour de la session est incomplete et donc le check data plante. a voir........

**Comment by thierry-thevenet** [comment]
fait sauf desynchro en 0.9.9
