### ISSUE TITLE
Lien skills expérience et skills self claim

### ISSUE THREAD

**Issue by Drax35** [thierrythevenet1963/Talao#283]
retour : "Quand on rentre ses expériences, les Skills sont demandés en remplissage obligatoire, mais ne sont ensuite pas repris dans la partie "Skills" ou il faut les re remplir... du coup je trouverais plus logique de faire le lien entre les 2 remplissages et de retrouver dans "skills" ce que j'ai complété dans "expérience""

**Comment by thierry-thevenet** [comment]
0.9.9
