### ISSUE TITLE
Fixer la taille de la photo de profil

### ISSUE THREAD

**Issue by Drax35** [thierrythevenet1963/Talao#288]
Fixer la taille de la photo de profil permettrait d'homogénéiser le design de tous les CV. Il faudrait pouvoir recadrer son image au moment de l'upload comme sur beaucoup d'autres sites (facebook, linkedin, instagram)

**Comment by thierry-thevenet** [comment]
je te laisse le faire... c est super penible ce genre de manip (recadrer l image...).
fichier main.py (cf repo) fonction picture().
Repartir du main du repo parceque j ai commençé a restructurer main.py pour en diminuer la taille.
