### ISSUE TITLE
Ajout page déconnexion après inactivité ou retour login

### ISSUE THREAD

**Issue by Drax35** [thierrythevenet1963/Talao#345]
Après un moment d'inactivité, le user est automatiquement déconnecté et le site renvoie une erreur. Ajouter une page déconnexion ou renvoyer directement au login.

**Comment by thierry-thevenet** [comment]
le handler est fait, il faudrait maintenant une page
403.html : pour la connexion refusée (inactivité)
404.html : pour la page not found

**Comment by thierry-thevenet** [comment]
redirect vers login
