### ISSUE TITLE
texte message

### ISSUE THREAD

**Issue by thierry-thevenet** [thierrythevenet1963/Talao#463]
invite_to_join.html : utiliser Identité Digitale plutot que blockchain workspace qui n a pas de sens pour un utilisateur
certificate_issued_issuer.html :majuscule a "data"
register.html : retirer l info sur address et did. il faut rester simple pour que l utisateur puisse avant toute chose se reconnecter
request_partnership.html : a discuter le contenu du message. le lien ne renvoie que sur un login et pas sur une page de consentement.

**Comment by AlexLeclerc102** [comment]
Pour request_partnership il faudrait en parler
