### ISSUE TITLE
bug report dans les vues externes

### ISSUE THREAD

**Issue by thierry-thevenet** [thierrythevenet1963/Talao#477]
lorsque l on affiche un certificat depuis un lien:
https://talao.co/certificate/?certificate_id=did:talao:talaonet:5aE452b6fD5d77dB83F7c617299b6DA88abA915D:document:14

on a acces au bug report mais il y a un probleme d email cette fois....

**Comment by AlexLeclerc102** [comment]
Il n'apparaît pas dans mon cas
